Repository EVeryCharge/EVeryCharge-Api-Server, pull requests merged in 2024-02, with the labels that each got.

#45 Feature/operating company entity
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryCustom.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryImpl.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/entity/OperatingCompany.java
  src/main/resources/application.yml
  src/main/resources/csv/chargingStationV3.CSV
  src/main/resources/sql/data.sql
Labels: enhancement

#47 지역, 세부지역, 운영기관 데이터 init 수정
  src/main/resources/application.yml
  src/main/resources/sql/data1.sql
  src/main/resources/sql/data2.sql
  src/main/resources/sql/data3.sql
Labels: bug

#51 feat : 배포 세팅
  Dockerfile
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: deploy

#54 remove : 테스트 파일 제거
  src/test/java/com/ll/eitcharge/EItChargeApplicationTests.java
Labels: deploy

#55 remove : 테스트 파일 제거 (#54)
  src/test/java/com/ll/eitcharge/EItChargeApplicationTests.java
Labels: deploy

#57 rollback, feat: 샘플 데이터 프로파일 수정
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: bug, deploy

#58 프로파일 수정
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: bug, deploy

#60 데이터 import(전국 충전소, 충전기 데이터)
  src/main/resources/csv/README.md
  src/main/resources/csv/charger.csv
  src/main/resources/csv/charger_sample_v1.csv
  src/main/resources/csv/chargingStation.csv
  src/main/resources/csv/chargingStationV3.CSV
  src/main/resources/csv/charging_station_sample_v3.csv
Labels: enhancement

#61 fix : proxy 변경
  front/package.json
Labels: bug, deploy

#62 Hotfix/prod fix
  front/package.json
Labels: bug, deploy

#63 fix : endpoint Fix
  front/src/components/AuthContext.js
  front/src/components/ChargingStationStateTable.js
  front/src/components/ReportDetail.js
  front/src/components/ReportForm.js
  front/src/components/ReportList.js
  front/src/components/Review.js
  front/src/containers/MapContainer.js
  front/src/pages/Login/Login.js
  front/src/pages/Signup/Signup.js
Labels: bug, deploy

#64 Hotfix/api end point fix
  front/src/components/AuthContext.js
  front/src/components/ChargingStationStateTable.js
  front/src/components/ReportDetail.js
  front/src/components/ReportForm.js
  front/src/components/ReportList.js
  front/src/components/Review.js
  front/src/containers/MapContainer.js
  front/src/pages/Login/Login.js
  front/src/pages/Signup/Signup.js
Labels: bug, deploy

#65 fix : endpoint Fix
  front/src/containers/modal/ChargerInfoModal.js
Labels: bug, deploy

#66 fix : endpoint Fix
  front/src/containers/modal/ChargerInfoModal.js
Labels: bug, deploy

#68 docs : 3주차 위클리
  Weekly_Log/[3주차] E-IT-Charge_8팀_진행상황_공유.md
Labels: documentation

#70 Hotfix/env setting
  front/.env.development
  front/.env.production
  front/package.json
  front/src/components/AuthContext.js
  front/src/components/ChargingStationStateTable.js
  front/src/containers/MapContainer.js
  front/src/pages/Login/Login.js
  front/src/services/HttpService.js
Labels: bug, enhancement, deploy

#71 Hotfix/env setting
  front/.env.development
  front/.env.production
  front/package.json
  front/src/components/AuthContext.js
  front/src/components/ChargingStationStateTable.js
  front/src/containers/MapContainer.js
  front/src/pages/Login/Login.js
  front/src/services/HttpService.js
Labels: bug, deploy

#73 샘플 데이터 생성 중 오류 수정
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/service/TechnicalManagerService.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: bug

#75 충전소 검색 API 구현, 로그인 오류 수정
  front/src/App.js
  front/src/components/Review.js
  front/src/pages/Error/ErrorPage.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Report/ReportForm.js
  front/src/pages/Report/ReportList.js
  front/src/services/HttpService.js
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDtoWithExecuteTime.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryCustom.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryImpl.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/entity/OperatingCompany.java
  src/main/java/com/ll/eitcharge/domain/region/region/entity/Region.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/entity/RegionDetail.java
Labels: bug, enhancement

#78 카카오 로그인
  front/src/components/AuthContext.js
  front/src/components/KakaoLoginButton.js
  front/src/components/UsernameStorage.js
  front/src/layout/NavBar.js
  front/src/pages/Login/Login.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/SocialMemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/dto/MemberDto.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/MemberService.java
  src/main/java/com/ll/eitcharge/global/rq/Rq.java
  src/main/java/com/ll/eitcharge/global/security/ASuccessHandler.java
  src/main/java/com/ll/eitcharge/global/security/CustomAuthenticationSuccessHandler.java
  src/main/java/com/ll/eitcharge/global/security/CustomOAuth2UserService.java
  src/main/java/com/ll/eitcharge/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#79 카카오 로그인 (#78)
  front/src/components/AuthContext.js
  front/src/components/KakaoLoginButton.js
  front/src/components/UsernameStorage.js
  front/src/layout/NavBar.js
  front/src/pages/Login/Login.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/SocialMemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/dto/MemberDto.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/MemberService.java
  src/main/java/com/ll/eitcharge/global/rq/Rq.java
  src/main/java/com/ll/eitcharge/global/security/ASuccessHandler.java
  src/main/java/com/ll/eitcharge/global/security/CustomAuthenticationSuccessHandler.java
  src/main/java/com/ll/eitcharge/global/security/CustomOAuth2UserService.java
  src/main/java/com/ll/eitcharge/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: deploy

#80 fix : yml 변경
  src/main/resources/application.yml
Labels: bug, deploy

#81 Hotfix/yml change
  src/main/resources/application.yml
Labels: bug, deploy

#83 Release/0206 2
  front/src/components/KakaoLoginButton.js
Labels: bug, deploy

#85 Release/0206 3
  src/main/java/com/ll/eitcharge/global/security/ASuccessHandler.java
Labels: bug, deploy

#87 Feature/station detail
  front/src/App.js
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Common/ChargingStationStateTable.js
  front/src/components/Common/GoBackButton.js
  front/src/components/Layout/Footer.css
  front/src/components/Layout/Footer.js
  front/src/components/Layout/NavBar.js
  front/src/components/UI/ChargerInfoBottomSheet.js
  front/src/components/UI/ChargerInfoCardView.js
  front/src/components/UI/ChargerInfoModal.js
  front/src/components/UI/ChargerInfoSidebar.js
  front/src/components/UI/ChargerInfoTooltip.js
  front/src/pages/Error/ErrorPage.js
  front/src/pages/Home/Home.js
  front/src/pages/Login/KakaoLoginButton.js
  front/src/pages/Login/Login.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Report/ReportForm.js
  front/src/pages/Report/ReportHeader.js
  front/src/pages/Report/ReportList.js
  front/src/pages/Review/Review.js
  front/src/utils/AuthContext.js
  front/src/utils/RedirectIfNotLoggedIn.js
  front/src/utils/UsernameStorage.js
Labels: enhancement

#90 카카오 로그인 리다렉션 오류, 회원가입, 로그인 UI 개선, 회원가입 오류
  front/src/assets/kakao_login.png
  front/src/components/Layout/NavBar.js
  front/src/pages/Login/KakaoLoginButton.js
  front/src/pages/Login/Login.js
  front/src/pages/Signup/Signup.js
  front/src/utils/UsernameStorage.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/global/security/ASuccessHandler.java
Labels: bug, enhancement

#91 Release/0207
  front/src/App.js
  front/src/assets/image/github-logo.png
  front/src/assets/kakao_login.png
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Common/ChargingStationStateTable.js
  front/src/components/Common/GoBackButton.js
  front/src/components/KakaoLoginButton.js
  front/src/components/Layout/Footer.css
  front/src/components/Layout/Footer.js
  front/src/components/Layout/NavBar.js
  front/src/components/UI/ChargerInfoBottomSheet.css
  front/src/components/UI/ChargerInfoBottomSheet.js
  front/src/components/UI/ChargerInfoCardView.css
  front/src/components/UI/ChargerInfoCardView.js
  front/src/components/UI/ChargerInfoModal.js
  front/src/components/UI/ChargerInfoSidebar.css
  front/src/components/UI/ChargerInfoSidebar.js
  front/src/components/UI/ChargerInfoTooltip.css
  front/src/components/UI/ChargerInfoTooltip.js
  front/src/pages/Error/ErrorPage.js
  front/src/pages/Home/Home.js
  front/src/pages/Login/KakaoLoginButton.js
  front/src/pages/Login/Login.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Report/ReportForm.js
  front/src/pages/Report/ReportHeader.js
  front/src/pages/Report/ReportList.js
  front/src/pages/Review/Review.js
  front/src/pages/Signup/Signup.js
  front/src/utils/AuthContext.js
  front/src/utils/RedirectIfNotLoggedIn.js
  front/src/utils/UsernameStorage.js
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/entity/OperatingCompany.java
  src/main/java/com/ll/eitcharge/global/security/ASuccessHandler.java
  src/main/resources/application.yml
Labels: bug, deploy

#93 충전소 상세 페이지 구현
  front/src/App.js
  front/src/components/ChargingStationInfo.js
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Common/ChargingStationStateTable.js
  front/src/components/UI/ChargerInfoModal.js
  front/src/pages/Home/Home.js
  front/src/pages/Review/Review.js
  front/src/utils/StationInfoContext.js
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargerStateDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
Labels: bug, enhancement

#97 리뷰디자인 수정
  front/src/pages/Review/Review.js
  src/main/java/com/ll/eitcharge/domain/review/review/controller/ReviewController.java
  src/main/java/com/ll/eitcharge/domain/review/review/dto/ReviewDto.java
  src/main/java/com/ll/eitcharge/domain/review/review/repository/ReviewRepository.java
  src/main/java/com/ll/eitcharge/domain/review/review/service/ReviewService.java
Labels: enhancement

#98 검색 기능 구현 완료
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Review/Review.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchBar.js
  front/src/pages/Search/ChargingStationSearchMap.js
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/ChargerType.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchBaseDistanceResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchItemResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDtoWithExecuteTime.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryCustom.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryImpl.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationSearchRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/repository/OperatingCompanyRepository.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/service/OperatingCompanyService.java
  src/main/java/com/ll/eitcharge/domain/region/RegionRepository.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/repository/RegionDetailRepository.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/service/RegionDetailService.java
  src/main/java/com/ll/eitcharge/domain/region/service/RegionService.java
Labels: enhancement

#99 Release/0212
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/ChargingStationInfo.js
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Common/ChargingStationStateTable.js
  front/src/components/Layout/NavBar.js
  front/src/components/UI/ChargerInfoModal.js
  front/src/pages/Home/Home.js
  front/src/pages/Review/Review.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchBar.js
  front/src/pages/Search/ChargingStationSearchMap.js
  front/src/utils/StationInfoContext.js
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/ChargerType.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargerStateDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchBaseDistanceResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchItemResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDtoWithExecuteTime.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryCustom.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepositoryImpl.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationSearchRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/repository/OperatingCompanyRepository.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/service/OperatingCompanyService.java
  src/main/java/com/ll/eitcharge/domain/region/RegionRepository.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/repository/RegionDetailRepository.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/service/RegionDetailService.java
  src/main/java/com/ll/eitcharge/domain/region/service/RegionService.java
  src/main/java/com/ll/eitcharge/domain/review/review/controller/ReviewController.java
  src/main/java/com/ll/eitcharge/domain/review/review/dto/ReviewDto.java
  src/main/java/com/ll/eitcharge/domain/review/review/repository/ReviewRepository.java
  src/main/java/com/ll/eitcharge/domain/review/review/service/ReviewService.java
Labels: bug, enhancement, deploy

#100 docs : 4주차 위클리
  Weekly_Log/[4주차] E-IT-Charge_8팀_진행상황_공유.md
Labels: documentation

#103 fix: TechnicalManager <-> ChargingStation 양방향 → 단방향 매핑으로 수정
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
Labels: bug

#104 Feature/inquiry board
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Inquiry/InqueryComment.js
  front/src/pages/Inquiry/Inquiry.js
  front/src/pages/Inquiry/InquiryCommentForm.js
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
  front/src/pages/Inquiry/InquiryModifyform.js
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/controller/CommentController.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentModifyRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentModifyResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/entity/Comment.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/repository/CommentRepository.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/service/CommentService.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/controller/InquiryController.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/entity/Inquiry.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/repository/InquiryRepository.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/service/InquiryService.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: enhancement

#105 충전기 상태 업데이트 스케줄러 개발
  batch/NoCharger.txt
  batch/NoChargingStation.txt
  build.gradle
  front/package-lock.json
  front/src/assets/image/kakao_login.png
  front/src/components/Common/ChargingStationMap.js
  front/src/pages/Login/KakaoLoginButton.js
  log/schedulerCompletLog.txt
  src/main/java/com/ll/eitcharge/EItChargeApplication.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/StreamItem.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/global/exceptions/GlobalException.java
  src/main/resources/application.yml
Labels: enhancement

#108 Bugfix/station search
  batch/NoCharger.txt
  batch/NoChargingStation.txt
  front/src/assets/image/marker.png
  front/src/assets/image/selectMarker.png
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchBar.js
  front/src/pages/Search/ChargingStationSearchMap.js
  front/src/pages/Search/ChargingStationSearchSwitch.js
  log/schedulerCompletLog.txt
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: bug, enhancement

#109 Feature/inquiry board
  Weekly_Log/[4주차] E-IT-Charge_8팀_진행상황_공유.md
  batch/NoCharger.txt
  batch/NoChargingStation.txt
  build.gradle
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/assets/image/kakao_login.png
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Inquiry/InqueryComment.js
  front/src/pages/Inquiry/Inquiry.js
  front/src/pages/Inquiry/InquiryCommentForm.js
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
  front/src/pages/Inquiry/InquiryModifyform.js
  front/src/pages/Login/KakaoLoginButton.js
  log/schedulerCompletLog.txt
  src/main/java/com/ll/eitcharge/EItChargeApplication.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/StreamItem.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/controller/CommentController.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentModifyRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentModifyResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/dto/CommentResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/entity/Comment.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/repository/CommentRepository.java
  src/main/java/com/ll/eitcharge/domain/inquiry/comment/service/CommentService.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/controller/InquiryController.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/entity/Inquiry.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/repository/InquiryRepository.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/service/InquiryService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/global/exceptions/GlobalException.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
  src/main/resources/application.yml
Labels: bug

#110 Release/0214
  batch/NoCharger.txt
  front/src/assets/image/marker.png
  front/src/assets/image/selectMarker.png
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Inquiry/Inquiry.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchBar.js
  front/src/pages/Search/ChargingStationSearchMap.js
  front/src/pages/Search/ChargingStationSearchSwitch.js
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
Labels: bug, enhancement, deploy

#117 운영 환경 UX / 성능 개선을 위한 최적화 및 권한 제어
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchMap.js
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
Labels: enhancement

#118 Feature/optimize prod
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/resources/application.yml
Labels: bug, enhancement, deploy

#123 메인화면 디자인 수정
  batch/NoCharger.txt
  batch/NoChargingStation.txt
  front/package-lock.json
  front/package.json
  front/src/assets/image/banner1.png
  front/src/assets/image/banner2.png
  front/src/assets/image/banner3.png
  front/src/assets/image/banner4.png
  front/src/assets/image/check.png
  front/src/assets/image/counter.png
  front/src/assets/image/docs.png
  front/src/assets/image/ev.png
  front/src/assets/image/map.png
  front/src/assets/image/mapSearch.png
  front/src/assets/image/soon.png
  front/src/assets/image/stastics.png
  front/src/components/Common/ChargingStationMap.js
  front/src/components/Layout/Footer.css
  front/src/components/Layout/Footer.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Home/Home.js
  front/src/pages/Inquiry/Inquiry.js
  log/schedulerCompletLog.txt
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: enhancement

#125 구글 서치콘솔 등록 DNS TXT 키 input
  front/public/android-icon-192x192.png
  front/public/apple-icon-192x192.png
  front/public/favicon-16x16.png
  front/public/favicon-32x32.png
  front/public/favicon-96x96.png
  front/public/favicon.ico
  front/public/index.html
  front/public/sitemap.xml
  front/public/thumbnail.png
Labels: enhancement

#126 feat: meta 키워드 추가
  front/public/index.html
Labels: enhancement

#127 네이버 서치 어드바이저 등록 DNS TXT 키 input
  front/public/index.html
Labels: enhancement

#128 디자인 수정
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Home/Home.js
  front/src/pages/Review/Review.js
  front/src/pages/Signup/Signup.js
Labels: enhancement

#134 프론트 UI / UX 조정
  front/package-lock.json
  front/src/pages/Login/Login.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchSwitch.js
  front/src/pages/Signup/Signup.js
Labels: bug

#135 Release/0216 4
  front/package-lock.json
  front/src/pages/Login/Login.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchSwitch.js
  front/src/pages/Signup/Signup.js
Labels: bug, deploy
