Repository EVeryCharge/EVeryCharge-Api-Server, pull requests merged in 2024-03, with the labels that each got.

#141 Feature/main gha
  .github/workflows/deploy.yml
  README.md
  infraScript/zero_downtime_deploy.py
Labels: enhancement

#146 웹 크롤링 SSL 문제 해결
  build.gradle
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
  src/main/resources/xls/charging_roaming_fee.xlsx
Labels: bug

#147 웹 크롤링 SSL 문제 해결
  build.gradle
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
  src/main/resources/xls/charging_roaming_fee.xlsx
Labels: deploy

#148 fix: 배포 자동화 트리거 브랜치 변경
  .github/workflows/deploy.yml
Labels: bug, deploy

#149 배포 자동화 브랜치 변경
  .github/workflows/deploy.yml
Labels: deploy

#151 Feature/scheduler improvement
  front/package-lock.json
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
Labels: enhancement

#153 웹 크롤링 SSL 문제 해결
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
Labels: bug

#155 docs: Weekly_log 추가(1주차, 2주차)
  Weekly_Log/[1주차] E-IT-Charge_고도화_5팀_진행상황_공유.md
  Weekly_Log/[2주차] E-IT-Charge_고도화_5팀_진행상황_공유.md
Labels: documentation

#156 yml 수정
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: enhancement

#159 feature : trigger instance-ids 변경
  .github/workflows/deploy.yml
Labels: enhancement

#160 Release/0313
  .github/workflows/deploy.yml
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/entity/ChargeFee.java
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-secret.yml.default
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: deploy

#161 파일 경로 불러오기 수정
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
  src/main/resources/xls/charge_roaming_fee.xlsx
Labels: bug

#162 release/0313-2
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
  src/main/resources/xls/charge_roaming_fee.xlsx
Labels: deploy

#163 충전기 상태 업데이트 개선
  build.gradle
  src/main/java/com/ll/eitcharge/EItChargeApplication.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/config/StreamItem.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/form/ChargerStateUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/repository/ChargerStateBulkUpdateRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/java/com/ll/eitcharge/global/redis/RedisConfig.java
  src/main/java/com/ll/eitcharge/standard/util/Ut.java
  src/main/resources/application-dev.yml
Labels: enhancement

#164 release/0314
  build.gradle
  src/main/java/com/ll/eitcharge/EItChargeApplication.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerScheduler/ChargerStatusScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/config/StreamItem.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/form/ChargerStateUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/repository/ChargerStateBulkUpdateRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/java/com/ll/eitcharge/global/redis/RedisConfig.java
  src/main/java/com/ll/eitcharge/standard/util/Ut.java
  src/main/resources/application-dev.yml
Labels: deploy

#165 Redis 로그 수정, 리팩토링
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
Labels: bug, enhancement

#166 release/0314-02
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/standard/util/ExcelDataUtil.java
Labels: deploy

#167 Feature/s3fileservice
  build.gradle
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/controller/InquiryController.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/entity/Inquiry.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/service/InquiryService.java
  src/main/java/com/ll/eitcharge/global/aws/s3/S3Config.java
  src/main/resources/application.yml
Labels: enhancement

#169 도커에서 사용하지 않는 리소스 정리
  .github/workflows/deploy.yml
Labels: enhancement

#170 release/0314-03
  .github/workflows/deploy.yml
  build.gradle
  front/src/components/Common/ChargingStationStateTable.js
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/controller/InquiryController.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryRequestDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/dto/InquiryResponseDto.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/entity/Inquiry.java
  src/main/java/com/ll/eitcharge/domain/inquiry/inquiry/service/InquiryService.java
  src/main/java/com/ll/eitcharge/global/aws/s3/S3Config.java
  src/main/java/com/ll/eitcharge/standard/util/Ut.java
  src/main/resources/application.yml
Labels: deploy

#171 성능 테스트(분기1)
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/repository/ChargerStateUpdateRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/java/com/ll/eitcharge/standard/util/Ut.java
Labels: enhancement

#172 release/0315-01
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/repository/ChargerStateUpdateRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/java/com/ll/eitcharge/standard/util/Ut.java
Labels: deploy

#173 성능 테스트(분기 2)
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
Labels: enhancement

#174 release/0315-02
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
Labels: deploy

#175 release/0315-02
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
Labels: deploy

#176 성능 테스트(분기 4)
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/resources/application.yml
Labels: enhancement

#177 release/0315-04
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/resources/application.yml
Labels: deploy

#179 release/0315-05
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
  src/main/java/com/ll/eitcharge/standard/util/Ut.java
Labels: deploy

#180 release/0315-05
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/resources/application.yml
Labels: deploy

#181 레디스 분기 1 로직 적용
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/resources/application.yml
Labels: enhancement

#185 redis 캐시워밍 사이즈 조절, AsyncConfig 수정
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/async/AsyncConfig.java
Labels: bug

#188 redis 캐시워밍 사이즈 조절
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
Labels: bug

#189 #release/0316-04
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
Labels: deploy

#192 레디스 분기 2 적용
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: bug

#194 redis 로직 2 수정
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: enhancement

#195 release/0316-07
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: deploy

#196 redis 로직 2 수정
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: bug

#197 release/0316-08
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: deploy

#198 신고기능 개선
  front/src/components/Layout/NavBar.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Report/ReportForm.js
  front/src/pages/Report/ReportHeader.js
  front/src/pages/Report/ReportList.js
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportPageResponseDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportResponseDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/service/ReportService.java
Labels: bug, enhancement

#200 docs: weekly 3주차
  Weekly_Log/[3주차] E-IT-Charge_고도화_5팀_진행상황_공유.md
Labels: documentation

#202 마이페이지
  front/src/App.js
  front/src/components/Layout/NavBar.js
  front/src/pages/Login/Login.js
  front/src/pages/Mypage/CarInit.js
  front/src/pages/Mypage/Edit.js
  front/src/pages/Mypage/My.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/dto/MemberCarDto.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/MemberService.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/controller/CarController.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/dto/CarDto.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/dto/CarListDto.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/dto/CarManufacturerDto.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/entity/Car.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/repository/CarRepository.java
  src/main/java/com/ll/eitcharge/domain/mypage/car/service/CarService.java
  src/main/resources/application.yml
  src/main/resources/sql/data4.sql
Labels: enhancement

#206 feat: pwa 적용
  front/package-lock.json
  front/package.json
  front/public/manifest.json
  front/src/index.js
  front/src/service-worker.js
  front/src/serviceWorkerRegistration.js
Labels: enhancement

#208 docs: 4주차 weekly 제출
  Weekly_Log/[4주차] E-IT-Charge-고도화_5팀_진행상황_공유.md
Labels: documentation

#207 일일단위 충전소 / 충전기 전역 업데이트
  batch/NoCharger.txt
  batch/NoChargingStation.txt
  build.gradle
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerApiItemForm.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerStateUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/config/StreamItem.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/config/ChargerBatchUpdateConfig.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargerApiBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargerBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargingStationBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/CompanyBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/reader/ChargerApiBatchReader.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/service/ChargerBatchUpdateService.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargerApiBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargerBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargingStationBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/CompanyBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/repository/ChargerStateUpdateRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateConfig.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationItemDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/HeaderDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ItemListDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/form/ChargingStationUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/entity/OperatingCompany.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/form/OperatingCompanyUpdateForm.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/sql/data2.sql
  src/main/resources/sql/data3.sql
  src/main/resources/sql/data_changed.sql
Labels: enhancement

#209 일일단위 충전소 / 충전기 전역 업데이트
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
Labels: enhancement

#210 release/0325-01
  batch/NoCharger.txt
  batch/NoChargingStation.txt
  build.gradle
  front/package-lock.json
  front/package.json
  front/public/manifest.json
  front/src/index.js
  front/src/service-worker.js
  front/src/serviceWorkerRegistration.js
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerApiItemForm.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerStateUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/config/StreamItem.java
  src/main/java/com/ll/eitcharge/domain/charger/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/config/ChargerBatchUpdateConfig.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargerApiBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargerBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargingStationBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/CompanyBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/reader/ChargerApiBatchReader.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/service/ChargerBatchUpdateService.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargerApiBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargerBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargingStationBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/CompanyBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/repository/ChargerStateUpdateRepository.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/scheduler/ChargerStateUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateConfig.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationItemDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/HeaderDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ItemListDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/form/ChargingStationUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/entity/OperatingCompany.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/form/OperatingCompanyUpdateForm.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/sql/data2.sql
  src/main/resources/sql/data3.sql
  src/main/resources/sql/data_changed.sql
Labels: deploy

#211 일일단위 충전소 / 충전기 전역 업데이트
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: bug, enhancement

#212 일일단위 충전소 / 충전기 전역 업데이트
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateRedisService.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/global/initData/All.java
Labels: bug

#213 release/0325-02
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
Labels: deploy

#216 충전소 요금기능 수정
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Common/CopyButton.js
  front/src/components/Common/KakaoMapButton.js
  front/src/components/Common/NaverMapButton.js
  front/src/pages/ChargeFee/ChargeFeeInfo.js
  front/src/pages/Report/ReportDetail.js
  front/src/pages/Report/ReportList.js
  log/schedulerCompletLog.txt
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/dto/ChargeFeeDto.java
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/entity/ChargeFee.java
  src/main/java/com/ll/eitcharge/domain/chargeFee/chargeFee/service/ChargeFeeService.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/form/ChargerUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/config/ChargerBatchUpdateConfig.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargerBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/ChargingStationBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/processor/CompanyBatchProcessor.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargerBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/ChargingStationBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/writer/CompanyBatchWriter.java
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/form/ChargingStationUpdateForm.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/entity/OperatingCompany.java
  src/main/java/com/ll/eitcharge/domain/operatingCompany/operatingCompany/form/OperatingCompanyUpdateForm.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-secret.yml.default
Labels: bug, enhancement

#219 현대차 정보 불러오기
  build.gradle
  front/src/assets/image/hyundai_login.png
  front/src/pages/Login/HyundaiLoginButton.js
  front/src/pages/Login/Login.js
  front/src/pages/Mypage/My.js
  src/main/java/com/ll/eitcharge/domain/charger/update/charger/batch/config/ChargerBatchUpdateConfig.java
  src/main/java/com/ll/eitcharge/domain/charger/update/chargerState/service/ChargerStateUpdateService.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/HyundaiMemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/HyundaiTokenService.java
Labels: enhancement

#223 현대차 불러오기
  front/src/pages/Login/HyundaiLoginButton.js
  front/src/pages/Mypage/CarInit.js
  front/src/pages/Mypage/My.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/HyundaiMemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/HyundaiTokenService.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/MemberService.java
  src/main/resources/application.yml
Labels: enhancement

#224 release/0326
  front/src/pages/Login/HyundaiLoginButton.js
  front/src/pages/Mypage/CarInit.js
  front/src/pages/Mypage/My.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/HyundaiMemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/HyundaiTokenService.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/MemberService.java
  src/main/resources/application.yml
Labels: deploy

#225 clientId 변경
  front/src/pages/Mypage/My.js
  src/main/java/com/ll/eitcharge/domain/member/member/service/HyundaiTokenService.java
  src/main/resources/application-dev.yml
Labels: enhancement

#226 release/0326-02
  front/src/pages/Mypage/My.js
  src/main/java/com/ll/eitcharge/domain/member/member/service/HyundaiTokenService.java
  src/main/resources/application-dev.yml
Labels: deploy

#227 everycharge로 변경
  .github/workflows/deploy.yml
  infraScript/zero_downtime_deploy.py
Labels: enhancement

#229 운영 DB 데이터 워밍
  src/main/java/com/ll/everycharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
Labels: enhancement

#231 release/0326-04
  front/src/components/Layout/Footer.js
  src/main/java/com/ll/everycharge/domain/charger/charger/form/ChargerApiItemForm.java
  src/main/resources/application-dev.yml
Labels: deploy

#232 도메인 변경에 따른 SEO
  front/public/android-icon-192x192.png
  front/public/apple-icon-192x192.png
  front/public/favicon-16x16.png
  front/public/favicon-32x32.png
  front/public/favicon-96x96.png
  front/public/favicon.ico
  front/public/index.html
  front/public/sitemap.xml
  front/public/thumbnail.png
Labels: enhancement

#234 client id 변경
  front/src/pages/Login/HyundaiLoginButton.js
Labels: enhancement

#237 모바일 기준 UI 개선
  front/src/components/Layout/NavBar.js
  front/src/pages/ChargeFee/ChargeFee.js
  front/src/pages/ChargeFee/ChargeFeeInfo.js
  front/src/pages/ChargeFee/ChargeRoamingFeeInfo.js
  front/src/pages/Home/Home.js
Labels: enhancement

#238 search UI 변경
  front/src/pages/Search/ChargingStationSearchBar.js
  front/src/pages/Search/ChargingStationSearchMap.js
Labels: enhancement

#242 OSIV 활성화, 배치 스케줄러 시간 수정
  front/package-lock.json
  src/main/java/com/ll/everycharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
  src/main/java/com/ll/everycharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/everycharge/domain/report/report/controller/ReportController.java
  src/main/resources/application.yml
Labels: bug, enhancement

#244 cron 시간 수정
  src/main/java/com/ll/everycharge/domain/charger/update/charger/scheduler/ChargerBatchUpdateScheduler.java
Labels: bug

#247 modal, navbar UI 변경
  front/package-lock.json
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Common/ChargingStationStateTable.js
  front/src/components/Layout/NavBar.js
  front/src/components/UI/ChargerInfoModal.js
  front/src/pages/Review/Review.js
  front/src/pages/Search/ChargingStationSearch.js
  front/src/pages/Search/ChargingStationSearchBar.js
Labels: enhancement

#249 Feature/s3fileservice
  front/package.json
  front/src/components/UI/ButtonStyles.css
  front/src/components/UI/ChargerInfoModal.js
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
  front/src/pages/Review/Review.js
Labels: enhancement

#250 충전기 상태 업데이트 미작동 수정
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/config/ChargerBatchUpdateConfig.java
Labels: bug

#251 release/0328-05
  front/package.json
  front/src/components/UI/ButtonStyles.css
  front/src/components/UI/ChargerInfoModal.js
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
  front/src/pages/Review/Review.js
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/config/ChargerBatchUpdateConfig.java
Labels: deploy

#252 UI detail 변경
  front/src/assets/image/hyundai_login.png
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Common/ChargingStationMap.js
  front/src/pages/Login/HyundaiLoginButton.js
  front/src/pages/Mypage/CarInit.js
  front/src/pages/Mypage/My.js
  front/src/pages/Review/Review.js
  front/src/pages/Search/ChargingStationSearchBar.js
  src/main/java/com/ll/everycharge/domain/member/member/service/HyundaiTokenService.java
Labels: enhancement

#253 release/0329
  front/src/assets/image/hyundai_login.png
  front/src/components/Common/ChargingStationInfo.js
  front/src/components/Common/ChargingStationMap.js
  front/src/pages/Login/HyundaiLoginButton.js
  front/src/pages/Mypage/CarInit.js
  front/src/pages/Mypage/My.js
  front/src/pages/Review/Review.js
  front/src/pages/Search/ChargingStationSearchBar.js
  src/main/java/com/ll/everycharge/domain/member/member/service/HyundaiTokenService.java
Labels: deploy

#254 Prodfileservice
  front/src/pages/Inquiry/InquiryDetail.js
  front/src/pages/Inquiry/InquiryForm.js
Labels: enhancement

#256 Update README.md
  README.md
Labels: documentation

#258 공간 인덱스 도입
  build.gradle
  src/main/java/com/ll/everycharge/domain/charger/charger/form/ChargerApiItemForm.java
  src/main/java/com/ll/everycharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/processor/ChargerApiBatchProcessor.java
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/reader/ChargerApiBatchReader.java
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/writer/ChargerApiBatchWriter.java
  src/main/java/com/ll/everycharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/everycharge/domain/chargingStation/chargingStation/repository/ChargingStationSearchRepository.java
  src/main/resources/sql/data_changed.sql
Labels: bug, enhancement

#259 공간 인덱스 도입 (#258)
  build.gradle
  src/main/java/com/ll/everycharge/domain/charger/charger/form/ChargerApiItemForm.java
  src/main/java/com/ll/everycharge/domain/charger/charger/service/ChargerService.java
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/processor/ChargerApiBatchProcessor.java
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/reader/ChargerApiBatchReader.java
  src/main/java/com/ll/everycharge/domain/charger/update/charger/batch/writer/ChargerApiBatchWriter.java
  src/main/java/com/ll/everycharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/everycharge/domain/chargingStation/chargingStation/repository/ChargingStationSearchRepository.java
  src/main/resources/sql/data_changed.sql
Labels: deploy
