Repository EVeryCharge/EVeryCharge-Api-Server, pull requests merged in 2024-01, with the labels that each got.

#2 Feature/login
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/AuthContext.js
  front/src/index.js
  front/src/layout/NavBar.js
  front/src/pages/Login/Login.js
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
Labels: enhancement

#8 Feature/cloud yml setting
  front/package-lock.json
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/resources/application.yml
Labels: enhancement

#10 Feature/entity setting
  src/main/java/com/ll/eitcharge/domain/agency/agency/entity/Agency.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/commentFile/commentFile/entity/CommentFile.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/rating/rating/entity/Rating.java
  src/main/java/com/ll/eitcharge/domain/region/region/entity/Region.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/Report.java
  src/main/java/com/ll/eitcharge/domain/review/review/entity/Review.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/entity/TechnicalManager.java
  src/main/resources/application-secret.yml.default
Labels: enhancement

#14 feature/report : 신고 기능 백엔드 로직 구현, 프론트 화면 구현
  front/src/App.js
  front/src/components/ReportDetail.js
  front/src/components/ReportList.js
  front/src/layout/NavBar.js
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/member/member/dto/MemberDto.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportRequestDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportResponseDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportResultRequestDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/Report.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/ReportType.java
  src/main/java/com/ll/eitcharge/domain/report/report/repository/ReportRepository.java
  src/main/java/com/ll/eitcharge/domain/report/report/service/ReportService.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/entity/TechnicalManager.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/repository/TechnicalManagerRepository.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/service/TechnicalManagerService.java
  src/main/java/com/ll/eitcharge/global/exceptions/GlobalException.java
  src/main/java/com/ll/eitcharge/global/jpa/entity/BaseTime.java
  src/main/resources/application-secret.yml.default
Labels: enhancement

#22 지역 테이블 데이터 파일 sql init 설정
  src/main/java/com/ll/eitcharge/domain/region/region/entity/Region.java
  src/main/resources/application.yml
  src/main/resources/sql/data.sql
Labels: bug, enhancement

#23 Feature/init data from csv
  Weekly_Log/[2주차] E-IT-Charge_8팀_진행상황_공유.md
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/charger/charger/repository/ChargerRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/region/region/entity/Region.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/entity/RegionDetail.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/service/RegionDetailService.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportRequestDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/Report.java
  src/main/java/com/ll/eitcharge/domain/review/review/entity/Review.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/entity/TechnicalManager.java
  src/main/resources/application.yml
  src/main/resources/csv/charger.csv
  src/main/resources/csv/chargingStation.csv
  src/main/resources/sql/csvImport.sql
  src/main/resources/sql/data.sql
Labels: bug, documentation, enhancement

#28 fix: data.sql 의존성 문제 해결(순서에 맞는 데이터 생성)
  src/main/resources/sql/data.sql
Labels: bug

#29 Feature/charging station pin render
  front/src/containers/MapContainer.js
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/Controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationSearchResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/region/region/entity/Region.java
  src/main/java/com/ll/eitcharge/domain/region/regionDetail/entity/RegionDetail.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/Report.java
  src/main/java/com/ll/eitcharge/domain/review/review/entity/Review.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/entity/TechnicalManager.java
Labels: enhancement

#32 회원가입 기능 구현
  front/src/App.js
  front/src/layout/NavBar.js
  front/src/pages/Login/Login.js
  front/src/pages/Signup/Signup.js
  src/main/java/com/ll/eitcharge/domain/member/member/controller/MemberController.java
  src/main/java/com/ll/eitcharge/domain/member/member/service/MemberService.java
Labels: enhancement

#33 Feature/review
  front/src/components/Review.js
  src/main/java/com/ll/eitcharge/domain/review/review/controller/ReviewController.java
  src/main/java/com/ll/eitcharge/domain/review/review/dto/ReviewDto.java
  src/main/java/com/ll/eitcharge/domain/review/review/entity/Review.java
  src/main/java/com/ll/eitcharge/domain/review/review/repository/ReviewRepository.java
  src/main/java/com/ll/eitcharge/domain/review/review/service/ReviewService.java
Labels: enhancement

#34 Feature/charger state info
  build.gradle
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/components/ChargingStationStateTable.js
  front/src/containers/modal/ChargerInfoModal.js
  src/main/java/com/ll/eitcharge/domain/charger/charger/entity/Charger.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargerStateDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationItemDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargingStationResponseDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/HeaderDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ItemListDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/resources/application.yml
Labels: enhancement

#35 신고기능 구현
  front/src/App.js
  front/src/components/ErrorPage.js
  front/src/components/GoBackButton.js
  front/src/components/RedirectIfNotLoggedIn.js
  front/src/components/ReportDetail.js
  front/src/components/ReportForm.js
  front/src/components/ReportHeader.js
  front/src/components/ReportList.js
  front/src/containers/modal/ChargerInfoModal.js
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/controller/ChargingStationController.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/dto/ChargerStateDto.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/entity/ChargingStation.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/repository/ChargingStationRepository.java
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/java/com/ll/eitcharge/domain/member/member/entity/Member.java
  src/main/java/com/ll/eitcharge/domain/report/report/controller/ReportController.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportCompleteRequestDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportRequestDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportResponseDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportResultRequestDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportSearchStationDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/dto/ReportSearchStationListResponseDto.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/Report.java
  src/main/java/com/ll/eitcharge/domain/report/report/entity/ReportType.java
  src/main/java/com/ll/eitcharge/domain/report/report/service/ReportService.java
  src/main/java/com/ll/eitcharge/domain/review/review/service/ReviewService.java
  src/main/java/com/ll/eitcharge/domain/technicalManager/technicalManager/service/TechnicalManagerService.java
  src/main/java/com/ll/eitcharge/global/app/AppConfig.java
  src/main/java/com/ll/eitcharge/global/initData/Dev.java
  src/main/java/com/ll/eitcharge/global/webMvc/CustomWebMvcConfig.java
Labels: bug, enhancement

#38 fix : findByLatBetweenAndLngBetween 파라미터 수정
  src/main/java/com/ll/eitcharge/domain/chargingStation/chargingStation/service/ChargingStationService.java
  src/main/resources/application.yml
Labels: bug
